Update edk2.yml

diff --git a/.github/workflows/edk2.yml b/.github/workflows/edk2.yml
--- a/.github/workflows/edk2.yml
+++ b/.github/workflows/edk2.yml
@@ -30,10 +30,10 @@ jobs:
         AVAIL_OVMF_V="$(curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} -s https://api.github.com/repos/ich777/mos-edk2-firmware/releases/latest | jq -r '.tag_name' | sed 's/^v//')"
 
         # Check if one of the versions is empty
-        #if [[ -z "${OVMF_V}" || -z "${AVAIL_OVMF_V}" ]]; then
-        #  echo "Can't get versions"
-        #  exit 1
-        #fi
+        if [[ -z "${OVMF_V}" || -z "${AVAIL_OVMF_V}" ]]; then
+          echo "Can't get versions"
+          exit 1
+        fi
 
         # Check versions
         if [ "${OVMF_V}" == "${AVAIL_OVMF_V}" ]; then
